name: CI/CD for NestJS

on:
  push:
    branches:
      - main  #  Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Change this to your Node.js version 

      - name: Install dependencies
        run: npm install

      - name: Build NestJS application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Change this to your main branch name

    steps:
      - name: Install SSH key
        id: install_ssh
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd NestJS-Hello-World
            git pull  # Pull latest changes
            npm install --production# Install production dependencies
            npm run build  # Build again (if necessary)
            sudo npm install -g pm2
            #npm run start
           
            pm2 restart ecosystem.config.js --env production  #  Restart PM2 (if using)

            
