name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

            PROJECT_DIR="/home/ubuntu/NestJS-Hello-World"

            # Remove the existing directory if it exists to avoid conflicts
            if [ -d "$PROJECT_DIR" ]; then
              rm -rf "$PROJECT_DIR"
            fi
            git clone https://github.com/priya2413/NestJS-Hello-World.git
            cd PROJECT_DIR
            # Pull the latest changes from the master branch
            git pull origin main
            npm install
            npm run build
            pm2 restart all || pm2 start --name "NestJS-Hello-World"
            
      
         
         
   
