name: CI/CD for NestJS-Hello-World

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ensure this matches your Node.js version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Archive files for deployment
        run: |
          tar -czf deployment.tar.gz ./*

      - name: Copy archive to EC2
        env:
          #SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan host >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa deployment.tar.gz username@host:/home/ubuntu/NestJS-Hello-World/deployment.tar.gz

      - name: Extract files on EC2 and restart application
        env:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa username@host<< 'EOF'
            tar -xzf /home/ubuntu/NestJS-Hello-World/deployment.tar.gz -C /home/ubuntu/NestJS-Hello-World
            cd /home/ubuntu/NestJS-Hello-World
            npm install --production
            pm2 restart ecosystem.config.js
          EOF
        shell: bash
