name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 'echo "SSH connection successful"'

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ubuntu@52.91.215.1:/home/ubuntu/NestJS-Hello-World

      - name: Debug Directory Structure
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 'ls -la /home/ubuntu/NestJS-Hello-World'

      - name: Install dependencies and restart application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 << 'EOF'
          cd /home/ubuntu/NestJS-Hello-World
          npm install
          npm run build
          pm2 restart NestJS-Hello-World || pm2 start dist/main.js --name "NestJS-Hello-World"
          EOF
