name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 'mkdir -p /home/ubuntu/NestJS-Hello-World'

      - name: Copy files to EC2
        run: |
          tar -czf code.tar.gz *
          scp -o StrictHostKeyChecking=no code.tar.gz ubuntu@52.91.215.1:/home/ubuntu/NestJS-Hello-World

      - name: Extract files on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 'cd /home/ubuntu/NestJS-Hello-World && tar -xzf code.tar.gz && rm code.tar.gz'

      - name: Install dependencies and restart application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 << 'EOF'
          cd /home/ubuntu/NestJS-Hello-World
          rm -rf node-modules package-lock.json
          npm install
          npm run build
          #npm start
          pm2 restart NestJS-Hello-World || pm2 start dist/main.js --name "NestJS-Hello-World"
          EOF
