name: CI/CD for NestJS-Hello-World

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: haripriya2413/NestJS-Hello-World
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build NestJS application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'  # Ensure this runs only on main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: haripriya2413/NestJS-Hello-World
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/nestjs/app
            git pull origin main
            npm install --production
            npm run build
            pm2 restart ecosystem.config.js
